### ISSUE TITLE
undefined method `paginate' for SnippetFile:Class

### ISSUE THREAD

**Issue by ghost** [radiant/radiant-snippets-extension#2]
probably missed a require or include or something

**Comment by jomz** [comment]
I also just encountered this with a new instance.
So has Andrew Vonderluft; https://github.com/radiant/radiant/issues/340

I guess SnippetFile is somehow loaded before Admin::ResourceController is

**Comment by simonhildebrandt** [comment]
+1 Just got this while upgrading a site.

**Comment by jomz** [comment]
It seems Admin::ResourceController is actually the issue here, the mechanism provided to turn pagination on or off doesn't seem to work.
In production mode, Admin::SnippetFilesController.paginated == true, so [Admin::ResourceController#160](https://github.com/radiant/radiant/blob/master/app/controllers/radiant/resource_controller.rb#L161) tries SnippetFile.paginate, which throws the exception as will_paginate does not work with non-AR classes.
In development mode, Admin::SnippetFilesController.paginated returns nil, and so do the Admin::Pages, ... controllers.

I tried but failed to turn off pagination, has anybody ever succeeded in this?

**Comment by antonjenkins** [comment]
Having the same problem after upgrading to 1.1.1

```
NoMethodError (undefined method `paginate' for SnippetFile:Class):
  radiant (1.1.1) app/controllers/admin/resource_controller.rb:160:in `load_models'
```

**Comment by mstarke** [comment]
This breaks the whole feature, any progress on a solution?

**Comment by saturnflyer** [comment]
So sorry everyone. I've released a new gem that just defines a paginate method on SnippetFile.
Thanks for reporting this.
